on:
  push: {}
  pull_request: {}
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 30
    outputs:
      checkout_commit: ${{ step.checkout.outputs.commit }}
    steps:
      - uses: actions/checkout@v5
        name: Checkout Code
        id: step-6e687384
        with:
          fetch-depth: 1
      - name: Echo
        run: 'echo "Checkout ref: ${{ step.step-6e687384.outputs.ref }}"'
      - name: Echo
        run: 'echo "Checkout commit: ${{ step.step-6e687384.outputs.commit }}"'
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444
        name: Setup Node
        id: step-0572bddc
        with:
          node-version: "20.4"
          always-auth: true
      - name: Echo
        run: echo "Hello, world!"
