name: CI Workflow
on:
  push:
    branches:
      - main
  pull_request: {}
jobs:
  test:
    uses: .github/workflows/shared-workflow.yml
    with:
      name: Test
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 1
      - name: Setup Node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903
        with:
          node-version: '18.17'
      - name: Save Cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: node_modules
          key: node_modules
      - name: Restore Cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: node_modules
          key: node_modules
      - name: Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Tests
        run: pytest
      - id: build-project
        name: Build Project
        run: npm run build
      - name: Upload Artifacts
        run: echo "Uploading from ${{ step.build-project.outputs.buildPath }}"
      - id: build-project2
        name: Build Project2
        run: npm run build
      - name: Upload Artifacts
        run: echo "Uploading from ${{ step.build-project2.outputs.buildPath }}"
      - name: Upload Build Artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          path: dist
          name: dist
      - name: Merge Build Artifacts
        uses: actions/upload-artifact/merge@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: dist
