name: Shared Workflow
on:
  workflow_call:
    inputs:
      name:
        description: The name of the project
        required: true
        default: My Project
jobs:
  test2:
    name: Test2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 1
      - name: Echo Current Ref
        run: "Current ref: ${{ step.checkout-id.outputs.ref }}"
      - name: Setup Node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903
        with:
          node-version: "18.17"
