name: Shared Workflow
on:
  workflow_call:
    inputs:
      name:
        description: The name of the project
        required: true
        default: My Project
jobs:
  test2:
    name: Test2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 1
