name: Security Scan
'on':
  schedule:
    - cron: 0 6 * * 1
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  actions: read
  contents: read
  security-events: write
jobs:
  analyze:
    runs-on:
      - ubuntu-latest
    strategy:
      matrix:
        language:
          - javascript
          - typescript
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
      - uses: github/codeql-action/analyze@v3
